export default [
    { 
        id: 1,
        cat: ['retail & entertainment'],
        name: '7Rewards',
        img: "https://cdn.codigo.co/uploads/2018/04/711.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'large',
        text: 'light',
        url: '/work/7-eleven',
        tag: '7-eleven',
    },
    { 
        id: 2,
        cat: ['telco'],
        name: 'MyRepublic Mobile',
        img: "https://cdn.codigo.co/uploads/2018/12/MYR.jpg",
        legends: ['app', 'uiux'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 3,
        cat: ['transport & logistics'],
        name: 'ComfortDelGro',
        img: "https://cdn.codigo.co/uploads/2018/08/CDG-2-1.jpg",
        legends: ['app'],
        size: 'small',
        text: 'dark',
    },
    { 
        id: 4,
        cat: ['retail & entertainment'],
        name: 'FairPrice Online',
        img: "https://cdn.codigo.co/uploads/2018/08/FPOL.jpg",
        legends: ['uiux'],
        size: 'large',
        text: 'light',
    },
    { 
        id: 5,
        cat:[ 'retail & entertainment'],
        name: 'Charles & Keith / Pedro',
        img: "https://cdn.codigo.co/uploads/2018/12/ck.jpg",
        legends: ['app'],
        size: 'large',
        text: 'dark',
    },
    { 
        id: 6,
        cat: ['retail & entertainment'],
        name: 'Justice League',
        img: "https://cdn.codigo.co/uploads/2018/11/thumbnail-justice_league@2x.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'large',
        text: 'light',
    },
    { 
        id: 7,
        cat:[ 'transport & logistics', 'co-incubation', 'start-ups'],
        name: 'FastFast',
        img: "https://cdn.codigo.co/uploads/2018/12/FF-1.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'large',
        text: 'light',
    },
    { 
        id: 8,
        cat: ['healthcare'],
        name: 'Fullerton Health',
        img: "https://cdn.codigo.co/uploads/2018/11/fullerton-health-thumbnail@2x.jpg",
        legends: ['app'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 9,
        cat: ['lifestyle'],
        name: 'Sky Premium',
        img: "https://cdn.codigo.co/uploads/2018/04/711.jpg",
        legends: ['app', 'web'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 10,
        cat: ['lifestyle'],
        name: 'T Singapore',
        img: "https://cdn.codigo.co/uploads/2018/12/TSingapore-thumbnail@2x.jpg",
        legends: ['web', 'cms'],
        size: 'large',
        text: 'light',
    },
    { 
        id: 11,
        cat: ['transport & logistics'],
        name: 'SingPost',
        img: "https://cdn.codigo.co/uploads/2018/12/singpost-thumbnail@2x.jpg",
        legends: ['app', 'uiux'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 12,
        cat: ['co-incubation', 'start-ups', 'food & beverage'],
        name: 'Dine Inn',
        img: "https://cdn.codigo.co/uploads/2018/12/dineinn.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 13,
        cat: ['transport & logistics'],
        name: 'Siemens Engineering',
        img: "https://cdn.codigo.co/uploads/2018/11/siemens.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 14,
        cat: [''],
        name: 'Singapore Grand Prix',
        img: "https://cdn.codigo.co/uploads/2018/12/f1.jpg",
        legends: ['app', 'web', 'cms'],
        size: 'small',
        text: 'light',
    },
    { 
        id: 15,
        cat: ['food & beverage'],
        name: "McDonald's",
        img: "https://cdn.codigo.co/uploads/2018/12/mc-cafe-thumbnail@2x.jpg",
        legends: ['app'],
        size: 'small',
        text: 'light',
    },
]